FROM node:20

WORKDIR /app

COPY package*.json /app/

RUN npm install -g pnpm

RUN pnpm create playwright

RUN pnpm install playwright

RUN pnpm exec playwright install --with-deps

COPY ./ /app/

ARG VITE_API_URL=${VITE_API_URL}
