services:
  db:
    restart: "no"
    ports:
      - "5432:5432"
  adminer:
    ports:
      - "8080:8080"
    depends_on:
      - db
  backend:
    restart: "no"
    ports:
      - "8000:8000"
    build:
      context: ./backend
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command:
      - fastapi
      - run
      - --reload
      - "app/src/main.py"
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
    volumes:
      - ./backend/htmlcov:/app/htmlcov
      - ./backend:/app
    environment:
      EMAILS_FROM_EMAIL: "noreply@example.com"
      ENVIRONMENT: "local"
  frontend:
    restart: "no"
    ports:
      - "3000:3000"
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${BACKEND_HOST?Variable not set}
        - NODE_ENV=development
    environment:
      HOST: 0.0.0.0
      NODE_ENV: development
      SENTRY_DSN: ${SENTRY_DSN}
      GOOGLE_CLIENT_ID: {$GOOGLE_CLIENT_ID}
      GOOGLE_REDIRECT_URI: {$GOOGLE_REDIRECT_URI}
      KLAVIYO_API_KEY: {$KLAVIYO_API_KEY}
      UMAMI_WEBSITE_ID: ${UMAMI_WEBSITE_ID}
    volumes:
      - ./frontend:/app
  playwright:
    build:
      context: ./frontend
      dockerfile: Dockerfile.playwright
      args:
        - VITE_API_URL=${BACKEND_HOST?Variable not set}
        - NODE_ENV=production
    ipc: host
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - VITE_API_URL=${BACKEND_HOST?Variable not set}
      - PLAYWRIGHT_HTML_HOST=0.0.0.0
      - CI=${CI}
    volumes:
      - ./frontend/blob-report:/app/blob-report
      - ./frontend/test-results:/app/test-results
    ports:
      - 9323:9323
